/**
 * In-memory fixture data used by optional UI fixture mode.
 *
 * These are deterministic, typed shapes that exercise the table/timeline
 * layouts without requiring the BFF to be running. Runtime review uses the
 * BFF-backed query functions unless VITE_USE_FIXTURES is explicitly set.
 */
import type {
  ApprovalPackageEntry,
  DecisionTrailEntry,
  EvalRunSummary,
  GrantEntry,
  ProviderEntry,
  ProviderModelEntry,
  RegistryEntry,
  RouteVersionEntry,
  RoutingEntry,
  ToolVerdictEntry,
  WorkflowEvent,
  WorkflowRunSummary,
} from "./types";

const NOW = Date.UTC(2026, 3, 29, 9, 0, 0);

const iso = (offsetSeconds: number) =>
  new Date(NOW + offsetSeconds * 1000).toISOString();

export const workflowRuns: WorkflowRunSummary[] = [
  {
    workflow_id: "uc3-2026-05-24-0001",
    run_id: null,
    workflow_type: "uc3_ifa_suitability_intake",
    status: "completed",
    current_step: "close",
    started_at: iso(-5400),
    closed_at: iso(-4920),
    updated_at: iso(-4920),
    correlation_id: "cor_uc3_ifa_demo_001",
    subject_id: "00000000-0000-4000-8000-000000000301",
    subject_ref: "advice_enquiry_2026_05_24_0001",
    subject_summary: "ISA investment advice - suitability report approval",
    subject_from: "web-advice@example.test",
    metadata: {
      source: "fixture",
      channel: "web-form",
      source_payload_ref: "payload_uc3_demo_001",
    },
  },
  {
    workflow_id: "uc2-2026-05-24-0001",
    run_id: null,
    workflow_type: "uc2_legal_services_intake_conflict_check",
    status: "completed",
    current_step: "close",
    started_at: iso(-3600),
    closed_at: iso(-3240),
    updated_at: iso(-3240),
    correlation_id: "cor_uc2_legal_demo_001",
    subject_id: "00000000-0000-4000-8000-000000000201",
    subject_ref: "legal_intake_2026_05_24_0001",
    subject_summary: "Commercial contract review - standard risk",
    subject_from: "legal-intake@example.test",
    metadata: {
      source: "fixture",
      channel: "email",
      source_payload_ref: "payload_uc2_demo_001",
    },
  },
  {
    workflow_id: "uc1-2026-04-29-0001",
    run_id: "01JT9VR1H6V7RZK1H6MB7VM3WX",
    workflow_type: "UC1 Enquiry Qualification",
    status: "running",
    current_step: "propose_send",
    started_at: iso(-1800),
    closed_at: null,
    updated_at: iso(-1750),
    correlation_id: "corr-9f3a14b1c0d8",
    subject_id: "00000000-0000-4000-8000-000000000001",
    subject_ref: "enq_2026_04_29_0001",
    subject_summary: "Household quote - flat-roof extension",
    subject_from: "buyer@acme.example",
    metadata: { source: "fixture" },
  },
  {
    workflow_id: "uc1-2026-04-29-0002",
    run_id: "01JT9VS2K0M9P5G1Q7H8XJN0AB",
    workflow_type: "UC1 Enquiry Qualification",
    status: "escalated",
    current_step: "escalate",
    started_at: iso(-7200),
    closed_at: null,
    updated_at: iso(-6900),
    correlation_id: "corr-7c4be9a1d22e",
    subject_id: "00000000-0000-4000-8000-000000000002",
    subject_ref: "enq_2026_04_29_0002",
    subject_summary: "Household renewal - prior escape-of-water claim",
    subject_from: "ops@globex.example",
    metadata: { source: "fixture" },
  },
  {
    workflow_id: "uc1-2026-04-29-0003",
    run_id: "01JT9VT3L1N0Q6H2R8J9YK1BCD",
    workflow_type: "UC1 Enquiry Qualification",
    status: "completed",
    current_step: "complete",
    started_at: iso(-86_400),
    closed_at: iso(-82_800),
    updated_at: iso(-82_800),
    correlation_id: "corr-2d5af0c3b914",
    subject_id: "00000000-0000-4000-8000-000000000003",
    subject_ref: "enq_2026_04_29_0003",
    subject_summary: "Contents cover enquiry - missing construction detail",
    subject_from: "alex.morgan@example.test",
    metadata: { source: "fixture" },
  },
];

export const workflowEvents: Record<string, WorkflowEvent[]> = {
  "uc3-2026-05-24-0001": [
    {
      id: "evt-uc3-001",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "enquiry.received",
      sequence: 1,
      step: "intake",
      occurred_at: iso(-5400),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        subject_summary: "ISA investment advice - suitability report approval",
        channel: "web-form",
        source_payload_ref: "payload_uc3_demo_001",
      },
    },
    {
      id: "evt-uc3-002",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 2,
      step: "intake",
      occurred_at: iso(-5380),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        channel: "web-form",
        advice_need_categories: ["pension_consolidation", "isa_investment"],
        attachment_count: 2,
      },
    },
    {
      id: "evt-uc3-003",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 3,
      step: "advice_scope_classification",
      occurred_at: iso(-5360),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        advice_scope_ref: "advice_scope_demo_001",
        advice_scope: "independent_retail_investment_advice",
        client_category: "retail_client",
        confidence: 0.91,
      },
    },
    {
      id: "evt-uc3-004",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 4,
      step: "fact_find_summary",
      occurred_at: iso(-5340),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        fact_find_summary_ref: "fact_find_demo_001",
        fact_find_completeness: "sufficient_for_initial_suitability",
        objective_refs: ["objective_demo_001"],
      },
    },
    {
      id: "evt-uc3-005",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 5,
      step: "attitude_to_risk_profile",
      occurred_at: iso(-5300),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        tool_name: "attitude_to_risk.profile",
        gateway_verdict: "allow",
        risk_profile_ref: "risk_profile_demo_001_v1",
      },
    },
    {
      id: "evt-uc3-006",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 6,
      step: "risk_profile_assessment",
      occurred_at: iso(-5260),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        risk_profile_ref: "risk_profile_demo_001_v1",
        risk_profile_status: "aligned",
        approval_required: false,
        confidence: 0.9,
      },
    },
    {
      id: "evt-uc3-007",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 7,
      step: "capacity_for_loss_assessment",
      occurred_at: iso(-5240),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        tool_name: "capacity_for_loss.assess",
        gateway_verdict: "allow",
        capacity_for_loss_ref: "capacity_for_loss_demo_001",
        capacity_for_loss_status: "sufficient",
      },
    },
    {
      id: "evt-uc3-008",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 8,
      step: "consumer_duty_support_assessment",
      occurred_at: iso(-5220),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        support_assessment_ref: "support_assessment_demo_001",
        support_status: "standard_support",
        vulnerability_marker_categories: [],
        approval_required: false,
      },
    },
    {
      id: "evt-uc3-009",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 9,
      step: "platform_research",
      occurred_at: iso(-5200),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        tool_name: "platform_research.run",
        gateway_verdict: "allow",
        platform_research_ref: "platform_research_demo_001_v1",
      },
    },
    {
      id: "evt-uc3-010",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 10,
      step: "suitability_conclusion",
      occurred_at: iso(-5020),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        suitability_conclusion_ref: "suitability_conclusion_demo_001",
        suitability_outcome: "suitable_subject_to_adviser_approval",
        policy_snapshot_ref: "policy_snapshot:uc3:default:v1",
      },
    },
    {
      id: "evt-uc3-011",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 11,
      step: "suitability_report_draft",
      occurred_at: iso(-5000),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        tool_name: "suitability_report.draft",
        gateway_verdict: "allow",
        suitability_report_ref: "suitability_report_demo_001",
      },
    },
    {
      id: "evt-uc3-012",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 12,
      step: "suitability_report_approval",
      occurred_at: iso(-4980),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        approval_required: true,
        approval_action: "suitability_report.issue.write",
        suitability_report_ref: "suitability_report_demo_001",
        suitability_conclusion_ref: "suitability_conclusion_demo_001",
      },
    },
    {
      id: "evt-uc3-013",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 13,
      step: "suitability_report_issue",
      occurred_at: iso(-4960),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        tool_name: "suitability_report.issue",
        gateway_verdict: "approval_required",
        approval_required: true,
        suitability_report_ref: "suitability_report_demo_001",
        suitability_conclusion_ref: "suitability_conclusion_demo_001",
      },
    },
    {
      id: "evt-uc3-014",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 14,
      step: "close",
      occurred_at: iso(-4940),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        outcome: "approval_required",
        final_summary: "suitability report issue requires approved Tool Gateway apply",
      },
    },
    {
      id: "evt-uc3-015",
      workflow_id: "uc3-2026-05-24-0001",
      event_type: "workflow.completed",
      sequence: 15,
      step: "close",
      occurred_at: iso(-4920),
      correlation_id: "cor_uc3_ifa_demo_001",
      payload: {
        advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
        outcome: "approval_required",
      },
    },
  ],
  "uc2-2026-05-24-0001": [
    {
      id: "evt-uc2-001",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "enquiry.received",
      sequence: 1,
      step: "intake",
      occurred_at: iso(-3600),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        subject_summary: "Commercial contract review - standard risk",
        channel: "email",
        source_payload_ref: "payload_uc2_demo_001",
      },
    },
    {
      id: "evt-uc2-002",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 4,
      step: "matter_classification",
      occurred_at: iso(-3560),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        matter_type: "commercial_contract",
        matter_scope_ref: "matter_scope_demo_001",
        confidence: 0.91,
      },
    },
    {
      id: "evt-uc2-003",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 5,
      step: "party_extraction",
      occurred_at: iso(-3530),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        party_graph_ref: "party_graph_demo_001",
        prospective_client_ref: "party_client_demo_001",
        authority_status: "confirmed",
      },
    },
    {
      id: "evt-uc2-004",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 6,
      step: "conflict_check",
      occurred_at: iso(-3500),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "conflict_check.search",
        gateway_verdict: "allow",
        conflict_check_ref: "conflict_check_demo_001",
      },
    },
    {
      id: "evt-uc2-005",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 7,
      step: "conflict_determination",
      occurred_at: iso(-3460),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        conflict_determination_ref: "conflict_determination_demo_001",
        conflict_status: "no_conflict",
        confidentiality_safeguard_status: "not_required",
      },
    },
    {
      id: "evt-uc2-006",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 8,
      step: "kyc_beneficial_ownership",
      occurred_at: iso(-3420),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "kyc_bo.lookup",
        gateway_verdict: "allow",
        cdd_record_ref: "cdd_record_demo_001",
        beneficial_ownership_status: "complete",
      },
    },
    {
      id: "evt-uc2-007",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 9,
      step: "aml_assessment",
      occurred_at: iso(-3380),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "aml_record_store.record_assessment",
        gateway_verdict: "allow",
        aml_risk_assessment_ref: "aml_risk_demo_001",
        aml_risk_rating: "standard",
      },
    },
    {
      id: "evt-uc2-008",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 10,
      step: "engagement_decision",
      occurred_at: iso(-3340),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        engagement_decision_ref: "engagement_decision_demo_001",
        engagement_outcome: "accept_for_engagement",
        policy_snapshot_ref: "policy_snapshot:uc2:default:v1",
      },
    },
    {
      id: "evt-uc2-009",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 11,
      step: "engagement_letter_draft",
      occurred_at: iso(-3310),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "engagement_letter.draft",
        gateway_verdict: "allow",
        engagement_letter_ref: "engagement_letter_demo_001",
      },
    },
    {
      id: "evt-uc2-010",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 12,
      step: "engagement_letter_send",
      occurred_at: iso(-3280),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "engagement_letter.send",
        gateway_verdict: "approval_required",
        approval_required: true,
        engagement_letter_ref: "engagement_letter_demo_001",
      },
    },
    {
      id: "evt-uc2-011",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.completed",
      sequence: 13,
      step: "close",
      occurred_at: iso(-3240),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        outcome: "approval_required",
      },
    },
  ],
  "uc1-2026-04-29-0001": [
    {
      id: "evt-001",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "workflow.started",
      occurred_at: iso(-1800),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { trigger: "mailpit.intake" },
    },
    {
      id: "evt-002",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "enquiry.parsed",
      occurred_at: iso(-1795),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { source: "mailpit", message_id: "<a1b2@acme.example>" },
    },
    {
      id: "evt-003",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "agent.invoked",
      occurred_at: iso(-1780),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { agent_id: "intake.classifier", invocation_id: "inv-aa01" },
    },
    {
      id: "evt-004",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "tool.call",
      occurred_at: iso(-1770),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { tool: "customer_profile.lookup", verdict: "allowed" },
    },
    {
      id: "evt-005",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "agent.responded",
      occurred_at: iso(-1750),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { agent_id: "intake.classifier", outcome: "answered" },
    },
  ],
};

export const decisionTrail: DecisionTrailEntry[] = [
  {
    id: "dec-uc3-001",
    workflow_id: "uc3-2026-05-24-0001",
    agent_id: "uc3.scope_classifier",
    agent_role: "advice_scope_classifier",
    invocation_id: "inv-uc3-001",
    prompt_ref: "prompts/uc3/scope-classifier/v1.md",
    prompt_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    model_route: "local/uc1-happy-path-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc3_advice_scope_classification",
    outcome: "succeeded",
    reasoning_summary:
      "Advice scope is independent retail investment advice with safe scope refs.",
    cost_usd: 0,
    latency_ms: 48,
    occurred_at: iso(-5360),
    correlation_id: "cor_uc3_ifa_demo_001",
    contract_refs: ["contracts/llm_provider/uc3_agent_io.schema.json"],
  },
  {
    id: "dec-uc3-002",
    workflow_id: "uc3-2026-05-24-0001",
    agent_id: "uc3.fact_find_summariser",
    agent_role: "fact_find_summariser",
    invocation_id: "inv-uc3-002",
    prompt_ref: "prompts/uc3/fact-find-summariser/v1.md",
    prompt_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    model_route: "local/uc1-happy-path-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc3_fact_find_summary",
    outcome: "succeeded",
    reasoning_summary:
      "Fact-find evidence is sufficient for initial suitability assessment.",
    cost_usd: 0,
    latency_ms: 50,
    occurred_at: iso(-5340),
    correlation_id: "cor_uc3_ifa_demo_001",
    contract_refs: ["contracts/llm_provider/uc3_agent_io.schema.json"],
  },
  {
    id: "dec-uc3-003",
    workflow_id: "uc3-2026-05-24-0001",
    agent_id: "uc3.risk_profile_assessor",
    agent_role: "risk_profile_assessor",
    invocation_id: "inv-uc3-003",
    prompt_ref: "prompts/uc3/risk-profile-assessor/v1.md",
    prompt_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    model_route: "local/uc1-happy-path-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc3_risk_profile_assessment",
    outcome: "succeeded",
    reasoning_summary:
      "Risk-profile refs align with the stated objective and no override is required.",
    cost_usd: 0,
    latency_ms: 53,
    occurred_at: iso(-5260),
    correlation_id: "cor_uc3_ifa_demo_001",
    contract_refs: ["contracts/llm_provider/uc3_agent_io.schema.json"],
  },
  {
    id: "dec-uc3-004",
    workflow_id: "uc3-2026-05-24-0001",
    agent_id: "uc3.support_assessor",
    agent_role: "consumer_duty_support_assessor",
    invocation_id: "inv-uc3-004",
    prompt_ref: "prompts/uc3/consumer-duty-support-assessor/v1.md",
    prompt_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    model_route: "local/uc1-happy-path-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc3_consumer_duty_support_assessment",
    outcome: "succeeded",
    reasoning_summary:
      "Consumer Duty support evidence indicates standard support with no handoff.",
    cost_usd: 0,
    latency_ms: 54,
    occurred_at: iso(-5220),
    correlation_id: "cor_uc3_ifa_demo_001",
    contract_refs: ["contracts/llm_provider/uc3_agent_io.schema.json"],
  },
  {
    id: "dec-uc3-005",
    workflow_id: "uc3-2026-05-24-0001",
    agent_id: "uc3.suitability_decider",
    agent_role: "suitability_decider",
    invocation_id: "inv-uc3-005",
    prompt_ref: "prompts/uc3/suitability-decider/v1.md",
    prompt_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    model_route: "local/uc1-happy-path-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc3_suitability_conclusion",
    outcome: "succeeded",
    reasoning_summary:
      "Suitability evidence refs are present and report issue requires adviser approval.",
    cost_usd: 0,
    latency_ms: 55,
    occurred_at: iso(-5020),
    correlation_id: "cor_uc3_ifa_demo_001",
    contract_refs: ["contracts/llm_provider/uc3_agent_io.schema.json"],
  },
  {
    id: "dec-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    agent_id: "uc2.legal_matter_classifier",
    agent_role: "legal_matter_classifier",
    invocation_id: "inv-uc2-001",
    prompt_ref: "prompts/uc2/legal-matter-classifier/v1.md",
    prompt_hash: "sha256:dbecd98c5b3c96713903f8ebd7c480d86adb02585a1a3d04c8d63a11bdf872bc",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000020",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc2_matter_classification",
    outcome: "succeeded",
    reasoning_summary:
      "Commercial contract matter classified with safe matter-scope refs.",
    cost_usd: 0,
    latency_ms: 42,
    occurred_at: iso(-3560),
    correlation_id: "cor_uc2_legal_demo_001",
    contract_refs: ["contracts/llm_provider/uc2_agent_io.schema.json"],
  },
  {
    id: "dec-uc2-002",
    workflow_id: "uc2-2026-05-24-0001",
    agent_id: "uc2.legal_party_extractor",
    agent_role: "legal_party_extractor",
    invocation_id: "inv-uc2-002",
    prompt_ref: "prompts/uc2/legal-party-extractor/v1.md",
    prompt_hash: "sha256:f4b1c9de5649601b29b23f477df016f554f9029ec24252b8cc49d2cde4674f01",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000021",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc2_party_extraction",
    outcome: "succeeded",
    reasoning_summary:
      "Party graph and authority evidence refs are complete for intake.",
    cost_usd: 0,
    latency_ms: 45,
    occurred_at: iso(-3530),
    correlation_id: "cor_uc2_legal_demo_001",
    contract_refs: ["contracts/llm_provider/uc2_agent_io.schema.json"],
  },
  {
    id: "dec-uc2-003",
    workflow_id: "uc2-2026-05-24-0001",
    agent_id: "uc2.conflict_analyst",
    agent_role: "conflict_analyst",
    invocation_id: "inv-uc2-003",
    prompt_ref: "prompts/uc2/conflict-analyst/v1.md",
    prompt_hash: "sha256:dbcaf349e3a5184d036c07560706207c6c0e8ef5630e1ead1a7cc77152290bec",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000022",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc2_conflict_determination",
    outcome: "succeeded",
    reasoning_summary:
      "Conflict search returned no conflict and no confidentiality safeguard is required.",
    cost_usd: 0,
    latency_ms: 47,
    occurred_at: iso(-3460),
    correlation_id: "cor_uc2_legal_demo_001",
    contract_refs: ["contracts/llm_provider/uc2_agent_io.schema.json"],
  },
  {
    id: "dec-uc2-004",
    workflow_id: "uc2-2026-05-24-0001",
    agent_id: "uc2.engagement_decider",
    agent_role: "engagement_decider",
    invocation_id: "inv-uc2-004",
    prompt_ref: "prompts/uc2/engagement-decider/v1.md",
    prompt_hash: "sha256:8f793f9105211157a8f2faead42229753d9b7574efc491515816cda7aecf58e2",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000023",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc2_engagement_decision",
    outcome: "succeeded",
    reasoning_summary:
      "No conflict, standard AML risk, and required SRA/AML evidence refs are present.",
    cost_usd: 0,
    latency_ms: 50,
    occurred_at: iso(-3340),
    correlation_id: "cor_uc2_legal_demo_001",
    contract_refs: ["contracts/llm_provider/uc2_agent_io.schema.json"],
  },
  {
    id: "dec-001",
    workflow_id: "uc1-2026-04-29-0001",
    agent_id: "intake.classifier",
    agent_role: "classifier",
    invocation_id: "inv-aa01",
    prompt_ref: "prompts/uc1/classifier/v1.md",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000001",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    outcome: "answered",
    reasoning_summary: "Inbound is a quote request; routed to commercial workstream.",
    cost_usd: 0.0042,
    latency_ms: 1820,
    occurred_at: iso(-1750),
    correlation_id: "corr-9f3a14b1c0d8",
  },
  {
    id: "dec-002",
    workflow_id: "uc1-2026-04-29-0002",
    agent_id: "renewal.assessor",
    agent_role: "request_drafter",
    invocation_id: "inv-bb14",
    prompt_ref: "prompts/uc1/request-drafter/v1.md",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000004",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: "provider_error",
    fallback_applied: true,
    outcome: "escalated",
    reasoning_summary: "Contract value above autonomous threshold; human approval required.",
    cost_usd: 0.0091,
    latency_ms: 2440,
    occurred_at: iso(-7000),
    correlation_id: "corr-7c4be9a1d22e",
  },
];

export const toolVerdicts: ToolVerdictEntry[] = [
  {
    id: "ver-uc3-001",
    workflow_id: "uc3-2026-05-24-0001",
    tool_name: "attitude_to_risk.profile",
    requested_mode: "read",
    enforced_mode: "read",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc3.risk_analyst",
    correlation_id: "cor_uc3_ifa_demo_001",
    occurred_at: iso(-5300),
  },
  {
    id: "ver-uc3-002",
    workflow_id: "uc3-2026-05-24-0001",
    tool_name: "capacity_for_loss.assess",
    requested_mode: "read",
    enforced_mode: "read",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc3.capacity_assessor",
    correlation_id: "cor_uc3_ifa_demo_001",
    occurred_at: iso(-5240),
  },
  {
    id: "ver-uc3-003",
    workflow_id: "uc3-2026-05-24-0001",
    tool_name: "platform_research.run",
    requested_mode: "read",
    enforced_mode: "read",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc3.research_analyst",
    correlation_id: "cor_uc3_ifa_demo_001",
    occurred_at: iso(-5200),
  },
  {
    id: "ver-uc3-004",
    workflow_id: "uc3-2026-05-24-0001",
    tool_name: "suitability_report.draft",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc3.suitability_decider",
    correlation_id: "cor_uc3_ifa_demo_001",
    occurred_at: iso(-5000),
  },
  {
    id: "ver-uc3-005",
    workflow_id: "uc3-2026-05-24-0001",
    tool_name: "suitability_report.issue",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "approval_required",
    reason: "Grant exists but requires adviser approval before connector execution.",
    redactions: [],
    caller_agent_id: "uc3.suitability_decider",
    correlation_id: "cor_uc3_ifa_demo_001",
    occurred_at: iso(-4960),
  },
  {
    id: "ver-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "conflict_check.search",
    requested_mode: "read",
    enforced_mode: "read",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc2.conflict_analyst",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3500),
  },
  {
    id: "ver-uc2-002",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "kyc_bo.lookup",
    requested_mode: "read",
    enforced_mode: "read",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc2.aml_assessor",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3420),
  },
  {
    id: "ver-uc2-003",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "aml_record_store.record_assessment",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc2.aml_assessor",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3380),
  },
  {
    id: "ver-uc2-004",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "engagement_letter.draft",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "allow",
    reason: "Grant accepted for requested tool and mode.",
    redactions: [],
    caller_agent_id: "uc2.engagement_decider",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3310),
  },
  {
    id: "ver-uc2-005",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "engagement_letter.send",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "approval_required",
    reason: "Grant exists but requires approval before connector execution.",
    redactions: [],
    caller_agent_id: "uc2.engagement_decider",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3280),
  },
  {
    id: "ver-001",
    workflow_id: "uc1-2026-04-29-0001",
    tool_name: "customer_profile.lookup",
    mode: "local",
    verdict: "allowed",
    reason: null,
    redactions: [],
    caller_agent_id: "intake.classifier",
    correlation_id: "corr-9f3a14b1c0d8",
    occurred_at: iso(-1770),
  },
  {
    id: "ver-002",
    workflow_id: "uc1-2026-04-29-0002",
    tool_name: "email.send",
    mode: "sandbox",
    verdict: "escalated",
    reason: "Approval required for outbound to renewal contact.",
    redactions: ["body.account_number"],
    caller_agent_id: "renewal.assessor",
    correlation_id: "corr-7c4be9a1d22e",
    occurred_at: iso(-6900),
  },
];

export const registry: RegistryEntry[] = [
  {
    agent_id: "intake.classifier",
    version: "v3",
    prompt_ref: "prompts/uc1/classifier/v1.md",
    model_route: "recorded-replay",
    description: "Classifies inbound emails into commercial workstreams.",
    updated_at: iso(-604_800),
  },
  {
    agent_id: "renewal.assessor",
    version: "v2",
    prompt_ref: "prompts/uc1/request-drafter/v1.md",
    model_route: "recorded-replay",
    description: "Assesses renewal opportunities and proposes next actions.",
    updated_at: iso(-1_209_600),
  },
];

export const grants: GrantEntry[] = [
  {
    grant_id: "grant-uc3-suitability-report-issue-write",
    agent_id: "uc3.suitability_decider",
    agent_version: "v1",
    tool_name: "suitability_report.issue",
    mode: "write",
    allowed: true,
    approval_required: true,
    redaction_policy: { redact_fields: [] },
    granted_at: iso(-2_592_000),
  },
  {
    grant_id: "grant-uc2-engagement-send-write",
    agent_id: "uc2.engagement_decider",
    agent_version: "v1",
    tool_name: "engagement_letter.send",
    mode: "write",
    allowed: true,
    approval_required: true,
    redaction_policy: { redact_fields: [] },
    granted_at: iso(-2_592_000),
  },
  {
    agent_id: "intake.classifier",
    tool_name: "customer_profile.lookup",
    mode: "local",
    scope: "read:contacts",
    approval_required: false,
    granted_at: iso(-2_592_000),
  },
  {
    agent_id: "renewal.assessor",
    tool_name: "email.send",
    mode: "sandbox",
    scope: "send:outbound",
    approval_required: true,
    granted_at: iso(-2_592_000),
  },
];

export const approvalPackages: ApprovalPackageEntry[] = [
  {
    id: "approval-uc3-001",
    workflow_id: "uc3-2026-05-24-0001",
    workflow_type: "uc3_ifa_suitability_intake",
    correlation_id: "cor_uc3_ifa_demo_001",
    approval_package_version: 1,
    approval_state: "requested",
    decision: null,
    reason_category: "tool_write_risk",
    agent_id: "uc3.suitability_decider",
    agent_version: "v1",
    requested_action: "suitability_report.issue.write",
    tool_name: "suitability_report.issue",
    requested_mode: "write",
    enforced_mode: "write",
    idempotency_key_ref:
      "sha256:3333333333333333333333333333333333333333333333333333333333333333",
    redaction_summary: {
      redaction_policy_ref:
        "tool_grant:grant-uc3-suitability-report-issue-write:redaction_policy",
      redacted_field_count: 0,
      redacted_field_refs: [],
    },
    subject_refs: {
      subject_ref: "advice_enquiry_2026_05_24_0001",
    },
    action_refs: {
      advice_enquiry_ref: "advice_enquiry_2026_05_24_0001",
      suitability_report_ref: "suitability_report_demo_001",
      suitability_conclusion_ref: "suitability_conclusion_demo_001",
      consumer_understanding_check_ref: "consumer_understanding_demo_001",
      conduct_hook_refs: [
        "conduct_fca_cobs_9_report",
        "conduct_fca_prin_2a_consumer_understanding",
        "conduct_fca_cobs_9_recordkeeping",
      ],
    },
    requested_at: iso(-4960),
    decision_due_at: iso(5400),
    expires_at: iso(9000),
    decision_at: null,
    source_audit_event_id: "ver-uc3-005",
    latest_audit_event_id: "ver-uc3-005",
    latest_verdict: "approval_required",
    latest_reason: "Grant exists but requires adviser approval before connector execution.",
    connector_invocation_id: null,
    grant_ref: "tool_grant:grant-uc3-suitability-report-issue-write",
    policy_version_refs: {
      approval_policy_ref: "approval_policy.suitability_report_issue_write.local.v1",
      sla_policy_ref: "approval_sla.suitability_report_issue_write.local.v1",
    },
    trace_join: {},
    updated_at: iso(-4960),
  },
  {
    id: "approval-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    workflow_type: "uc2_legal_services_intake_conflict_check",
    correlation_id: "cor_uc2_legal_demo_001",
    approval_package_version: 1,
    approval_state: "requested",
    decision: null,
    reason_category: "tool_write_risk",
    agent_id: "uc2.engagement_decider",
    agent_version: "v1",
    requested_action: "engagement_letter.send.write",
    tool_name: "engagement_letter.send",
    requested_mode: "write",
    enforced_mode: "write",
    idempotency_key_ref:
      "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    redaction_summary: {
      redaction_policy_ref: "tool_grant:grant-uc2-engagement-send-write:redaction_policy",
      redacted_field_count: 0,
      redacted_field_refs: [],
    },
    subject_refs: {
      subject_ref: "legal_intake_2026_05_24_0001",
    },
    action_refs: {
      legal_intake_ref: "legal_intake_2026_05_24_0001",
      engagement_letter_ref: "engagement_letter_demo_001",
      engagement_decision_ref: "engagement_decision_demo_001",
      conduct_hook_refs: [
        "conduct_sra_identify_client_8_1",
        "conduct_mlr_cdd_reg_27_28",
        "conduct_sra_accountability_7_1_7_2",
      ],
    },
    requested_at: iso(-3280),
    decision_due_at: iso(3600),
    expires_at: iso(7200),
    decision_at: null,
    source_audit_event_id: "ver-uc2-005",
    latest_audit_event_id: "ver-uc2-005",
    latest_verdict: "approval_required",
    latest_reason: "Grant exists but requires approval before connector execution.",
    connector_invocation_id: null,
    grant_ref: "tool_grant:grant-uc2-engagement-send-write",
    policy_version_refs: {
      approval_policy_ref: "approval_policy.engagement_letter_send_write.local.v1",
      sla_policy_ref: "approval_sla.engagement_letter_send_write.local.v1",
    },
    trace_join: {},
    updated_at: iso(-3280),
  },
];

export const routing: RoutingEntry[] = [
  {
    route_id: "rt-default",
    match: "classifier:enquiry_classification:demo",
    agent_role: "classifier",
    task_kind: "enquiry_classification",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider: "local",
    model: "uc1-happy-path-v1",
    parameters: { temperature: 0.2 },
    budget_usd: 0.01,
    fallback_policy: { on_provider_error: "escalate" },
    lifecycle_state: "approved",
  },
  {
    route_id: "rt-fallback",
    match: "request_drafter:missing_data_request_draft:demo",
    agent_role: "request_drafter",
    task_kind: "missing_data_request_draft",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider: "local",
    model: "uc1-happy-path-v1",
    parameters: { temperature: 0.3 },
    budget_usd: 0.01,
    fallback_policy: { on_provider_error: "escalate" },
    lifecycle_state: "approved",
  },
];

export const providers: ProviderEntry[] = [
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    display_name: "Local structured boundary",
    provider_kind: "local",
    lifecycle_state: "approved",
    credential_required: false,
    secret_ref_names: [],
    missing_credentials_behaviour: "allow",
    data_boundary: { mode: "local_only", stores_customer_content: false },
    operational_limits: { default_timeout_ms: 1000, max_retries: 0 },
    audit: { owner: "agent-runtime", change_ref: "2A-02" },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "deepseek",
    display_name: "DeepSeek API",
    provider_kind: "commercial",
    lifecycle_state: "disabled",
    credential_required: true,
    secret_ref_names: ["DEEPSEEK_API_KEY"],
    missing_credentials_behaviour: "disable_provider",
    data_boundary: { mode: "external_api", stores_customer_content: true },
    operational_limits: { default_timeout_ms: 30000, max_retries: 2 },
    audit: { owner: "agent-runtime", change_ref: "r4-provider-verification" },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "openai",
    display_name: "OpenAI API",
    provider_kind: "commercial",
    lifecycle_state: "disabled",
    credential_required: true,
    secret_ref_names: ["OPENAI_API_KEY"],
    missing_credentials_behaviour: "disable_provider",
    data_boundary: { mode: "external_api", stores_customer_content: true },
    operational_limits: { default_timeout_ms: 30000, max_retries: 2 },
    audit: { owner: "agent-runtime", change_ref: "r4-provider-verification" },
  },
];

export const providerModels: ProviderModelEntry[] = [
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    model_id: "uc1-happy-path-v1",
    display_name: "UC1 local structured model",
    lifecycle_state: "approved",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 8192,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0,
      output_usd_per_1m_tokens: 0,
    },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "deepseek",
    model_id: "deepseek-v4-flash",
    display_name: "DeepSeek V4 Flash",
    lifecycle_state: "disabled",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 1000000,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0.14,
      output_usd_per_1m_tokens: 0.28,
    },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "openai",
    model_id: "gpt-5.4-mini-2026-03-17",
    display_name: "GPT-5.4 mini pinned snapshot",
    lifecycle_state: "disabled",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 400000,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0.75,
      output_usd_per_1m_tokens: 4.5,
    },
  },
];

export const routeVersions: RouteVersionEntry[] = [
  {
    route_id: "11000000-0000-4000-8000-000000000004",
    route_version: 1,
    lifecycle_state: "approved",
    agent_role: "request_drafter",
    task_kind: "missing_data_request_draft",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider_catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    model_id: "uc1-happy-path-v1",
    parameters: { temperature: 0.3 },
    budget_usd: 0.01,
    max_latency_ms: 5000,
    fallback_policy: {
      mode: "escalate",
      fallback_reasons: ["provider_error", "timeout", "rate_limited", "budget_exceeded"],
    },
    eval_required: true,
    eval_fixture_refs: [
      "chorus/eval/fixtures/uc1_happy_path.json",
      "chorus/eval/fixtures/uc1_validator_redraft.json",
      "chorus/eval/fixtures/uc1_accepted_routing.json",
      "chorus/eval/fixtures/uc1_referred_routing.json",
      "chorus/eval/fixtures/uc1_declined_routing.json",
    ],
    promotion: { change_ref: "2A-02", approved_by: "architecture-docs" },
    created_at: iso(-2_592_000),
  },
];

export const evalRuns: EvalRunSummary[] = [
  {
    run_id: "eval-2026-04-28-1830",
    fixture: "uc1.golden",
    status: "passed",
    pass_count: 14,
    fail_count: 0,
    duration_ms: 38_400,
    finished_at: iso(-39_600),
  },
  {
    run_id: "eval-2026-04-28-1900",
    fixture: "uc1.escalation",
    status: "failed",
    pass_count: 11,
    fail_count: 2,
    duration_ms: 41_900,
    finished_at: iso(-37_200),
  },
];
