/**
 * In-memory fixture data used by optional UI fixture mode.
 *
 * These are deterministic, typed shapes that exercise the table/timeline
 * layouts without requiring the BFF to be running. Runtime review uses the
 * BFF-backed query functions unless VITE_USE_FIXTURES is explicitly set.
 */
import type {
  ApprovalPackageEntry,
  DecisionTrailEntry,
  EvalRunSummary,
  GrantEntry,
  ProviderEntry,
  ProviderModelEntry,
  RegistryEntry,
  RouteVersionEntry,
  RoutingEntry,
  ToolVerdictEntry,
  WorkflowEvent,
  WorkflowRunSummary,
} from "./types";

const NOW = Date.UTC(2026, 3, 29, 9, 0, 0);

const iso = (offsetSeconds: number) =>
  new Date(NOW + offsetSeconds * 1000).toISOString();

export const workflowRuns: WorkflowRunSummary[] = [
  {
    workflow_id: "uc2-2026-05-24-0001",
    run_id: null,
    workflow_type: "uc2_legal_services_intake_conflict_check",
    status: "completed",
    current_step: "close",
    started_at: iso(-3600),
    closed_at: iso(-3240),
    updated_at: iso(-3240),
    correlation_id: "cor_uc2_legal_demo_001",
    subject_id: "00000000-0000-4000-8000-000000000201",
    subject_ref: "legal_intake_2026_05_24_0001",
    subject_summary: "Commercial contract review - standard risk",
    subject_from: "legal-intake@example.test",
    metadata: {
      source: "fixture",
      channel: "email",
      source_payload_ref: "payload_uc2_demo_001",
    },
  },
  {
    workflow_id: "uc1-2026-04-29-0001",
    run_id: "01JT9VR1H6V7RZK1H6MB7VM3WX",
    workflow_type: "UC1 Enquiry Qualification",
    status: "running",
    current_step: "propose_send",
    started_at: iso(-1800),
    closed_at: null,
    updated_at: iso(-1750),
    correlation_id: "corr-9f3a14b1c0d8",
    subject_id: "00000000-0000-4000-8000-000000000001",
    subject_ref: "enq_2026_04_29_0001",
    subject_summary: "Household quote - flat-roof extension",
    subject_from: "buyer@acme.example",
    metadata: { source: "fixture" },
  },
  {
    workflow_id: "uc1-2026-04-29-0002",
    run_id: "01JT9VS2K0M9P5G1Q7H8XJN0AB",
    workflow_type: "UC1 Enquiry Qualification",
    status: "escalated",
    current_step: "escalate",
    started_at: iso(-7200),
    closed_at: null,
    updated_at: iso(-6900),
    correlation_id: "corr-7c4be9a1d22e",
    subject_id: "00000000-0000-4000-8000-000000000002",
    subject_ref: "enq_2026_04_29_0002",
    subject_summary: "Household renewal - prior escape-of-water claim",
    subject_from: "ops@globex.example",
    metadata: { source: "fixture" },
  },
  {
    workflow_id: "uc1-2026-04-29-0003",
    run_id: "01JT9VT3L1N0Q6H2R8J9YK1BCD",
    workflow_type: "UC1 Enquiry Qualification",
    status: "completed",
    current_step: "complete",
    started_at: iso(-86_400),
    closed_at: iso(-82_800),
    updated_at: iso(-82_800),
    correlation_id: "corr-2d5af0c3b914",
    subject_id: "00000000-0000-4000-8000-000000000003",
    subject_ref: "enq_2026_04_29_0003",
    subject_summary: "Contents cover enquiry - missing construction detail",
    subject_from: "alex.morgan@example.test",
    metadata: { source: "fixture" },
  },
];

export const workflowEvents: Record<string, WorkflowEvent[]> = {
  "uc2-2026-05-24-0001": [
    {
      id: "evt-uc2-001",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "enquiry.received",
      sequence: 1,
      step: "intake",
      occurred_at: iso(-3600),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        subject_summary: "Commercial contract review - standard risk",
        channel: "email",
        source_payload_ref: "payload_uc2_demo_001",
      },
    },
    {
      id: "evt-uc2-002",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 6,
      step: "conflict_check",
      occurred_at: iso(-3500),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        tool_name: "conflict_check.search",
        gateway_verdict: "allow",
        conflict_check_ref: "conflict_check_demo_001",
      },
    },
    {
      id: "evt-uc2-003",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.step.completed",
      sequence: 10,
      step: "engagement_decision",
      occurred_at: iso(-3340),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        engagement_decision_ref: "engagement_decision_demo_001",
        engagement_outcome: "accept_for_engagement",
        policy_snapshot_ref: "policy_snapshot:uc2:default:v1",
      },
    },
    {
      id: "evt-uc2-004",
      workflow_id: "uc2-2026-05-24-0001",
      event_type: "workflow.completed",
      sequence: 12,
      step: "close",
      occurred_at: iso(-3240),
      correlation_id: "cor_uc2_legal_demo_001",
      payload: {
        legal_intake_ref: "legal_intake_2026_05_24_0001",
        outcome: "approval_required",
      },
    },
  ],
  "uc1-2026-04-29-0001": [
    {
      id: "evt-001",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "workflow.started",
      occurred_at: iso(-1800),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { trigger: "mailpit.intake" },
    },
    {
      id: "evt-002",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "enquiry.parsed",
      occurred_at: iso(-1795),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { source: "mailpit", message_id: "<a1b2@acme.example>" },
    },
    {
      id: "evt-003",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "agent.invoked",
      occurred_at: iso(-1780),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { agent_id: "intake.classifier", invocation_id: "inv-aa01" },
    },
    {
      id: "evt-004",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "tool.call",
      occurred_at: iso(-1770),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { tool: "customer_profile.lookup", verdict: "allowed" },
    },
    {
      id: "evt-005",
      workflow_id: "uc1-2026-04-29-0001",
      event_type: "agent.responded",
      occurred_at: iso(-1750),
      correlation_id: "corr-9f3a14b1c0d8",
      payload: { agent_id: "intake.classifier", outcome: "answered" },
    },
  ],
};

export const decisionTrail: DecisionTrailEntry[] = [
  {
    id: "dec-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    agent_id: "uc2.engagement_decider",
    agent_role: "engagement_decider",
    invocation_id: "inv-uc2-001",
    prompt_ref: "prompts/uc2/engagement-decider/v1.md",
    prompt_hash: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
    model_route: "local/uc2-synthetic-v1",
    route_id: null,
    route_version: null,
    provider: "local",
    model: "uc2-synthetic-v1",
    fallback_reason: null,
    fallback_applied: false,
    task_kind: "uc2_engagement_decision",
    outcome: "succeeded",
    reasoning_summary:
      "No conflict, standard AML risk, and required SRA/AML evidence refs are present.",
    cost_usd: 0,
    latency_ms: 50,
    occurred_at: iso(-3340),
    correlation_id: "cor_uc2_legal_demo_001",
    contract_refs: ["contracts/llm_provider/uc2_agent_io.schema.json"],
  },
  {
    id: "dec-001",
    workflow_id: "uc1-2026-04-29-0001",
    agent_id: "intake.classifier",
    agent_role: "classifier",
    invocation_id: "inv-aa01",
    prompt_ref: "prompts/uc1/classifier/v1.md",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000001",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: null,
    fallback_applied: false,
    outcome: "answered",
    reasoning_summary: "Inbound is a quote request; routed to commercial workstream.",
    cost_usd: 0.0042,
    latency_ms: 1820,
    occurred_at: iso(-1750),
    correlation_id: "corr-9f3a14b1c0d8",
  },
  {
    id: "dec-002",
    workflow_id: "uc1-2026-04-29-0002",
    agent_id: "renewal.assessor",
    agent_role: "request_drafter",
    invocation_id: "inv-bb14",
    prompt_ref: "prompts/uc1/request-drafter/v1.md",
    model_route: "local/uc1-happy-path-v1",
    route_id: "11000000-0000-4000-8000-000000000004",
    route_version: 1,
    provider: "local",
    model: "uc1-happy-path-v1",
    fallback_reason: "provider_error",
    fallback_applied: true,
    outcome: "escalated",
    reasoning_summary: "Contract value above autonomous threshold; human approval required.",
    cost_usd: 0.0091,
    latency_ms: 2440,
    occurred_at: iso(-7000),
    correlation_id: "corr-7c4be9a1d22e",
  },
];

export const toolVerdicts: ToolVerdictEntry[] = [
  {
    id: "ver-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    tool_name: "engagement_letter.send",
    requested_mode: "write",
    enforced_mode: "write",
    verdict: "approval_required",
    reason: "Grant exists but requires approval before connector execution.",
    redactions: [],
    caller_agent_id: "uc2.engagement_decider",
    correlation_id: "cor_uc2_legal_demo_001",
    occurred_at: iso(-3280),
  },
  {
    id: "ver-001",
    workflow_id: "uc1-2026-04-29-0001",
    tool_name: "customer_profile.lookup",
    mode: "local",
    verdict: "allowed",
    reason: null,
    redactions: [],
    caller_agent_id: "intake.classifier",
    correlation_id: "corr-9f3a14b1c0d8",
    occurred_at: iso(-1770),
  },
  {
    id: "ver-002",
    workflow_id: "uc1-2026-04-29-0002",
    tool_name: "email.send",
    mode: "sandbox",
    verdict: "escalated",
    reason: "Approval required for outbound to renewal contact.",
    redactions: ["body.account_number"],
    caller_agent_id: "renewal.assessor",
    correlation_id: "corr-7c4be9a1d22e",
    occurred_at: iso(-6900),
  },
];

export const registry: RegistryEntry[] = [
  {
    agent_id: "intake.classifier",
    version: "v3",
    prompt_ref: "prompts/uc1/classifier/v1.md",
    model_route: "recorded-replay",
    description: "Classifies inbound emails into commercial workstreams.",
    updated_at: iso(-604_800),
  },
  {
    agent_id: "renewal.assessor",
    version: "v2",
    prompt_ref: "prompts/uc1/request-drafter/v1.md",
    model_route: "recorded-replay",
    description: "Assesses renewal opportunities and proposes next actions.",
    updated_at: iso(-1_209_600),
  },
];

export const grants: GrantEntry[] = [
  {
    grant_id: "grant-uc2-engagement-send-write",
    agent_id: "uc2.engagement_decider",
    agent_version: "v1",
    tool_name: "engagement_letter.send",
    mode: "write",
    allowed: true,
    approval_required: true,
    redaction_policy: { redact_fields: [] },
    granted_at: iso(-2_592_000),
  },
  {
    agent_id: "intake.classifier",
    tool_name: "customer_profile.lookup",
    mode: "local",
    scope: "read:contacts",
    approval_required: false,
    granted_at: iso(-2_592_000),
  },
  {
    agent_id: "renewal.assessor",
    tool_name: "email.send",
    mode: "sandbox",
    scope: "send:outbound",
    approval_required: true,
    granted_at: iso(-2_592_000),
  },
];

export const approvalPackages: ApprovalPackageEntry[] = [
  {
    id: "approval-uc2-001",
    workflow_id: "uc2-2026-05-24-0001",
    workflow_type: "uc2_legal_services_intake_conflict_check",
    correlation_id: "cor_uc2_legal_demo_001",
    approval_package_version: 1,
    approval_state: "requested",
    decision: null,
    reason_category: "tool_write_risk",
    agent_id: "uc2.engagement_decider",
    agent_version: "v1",
    requested_action: "engagement_letter.send.write",
    tool_name: "engagement_letter.send",
    requested_mode: "write",
    enforced_mode: "write",
    idempotency_key_ref:
      "sha256:2222222222222222222222222222222222222222222222222222222222222222",
    redaction_summary: {
      redaction_policy_ref: "tool_grant:grant-uc2-engagement-send-write:redaction_policy",
      redacted_field_count: 0,
      redacted_field_refs: [],
    },
    subject_refs: {
      subject_ref: "legal_intake_2026_05_24_0001",
    },
    action_refs: {
      legal_intake_ref: "legal_intake_2026_05_24_0001",
      engagement_letter_ref: "engagement_letter_demo_001",
      engagement_decision_ref: "engagement_decision_demo_001",
      conduct_hook_refs: [
        "conduct_sra_conflict_6_1_6_2",
        "conduct_mlr_cdd_reg_27_28",
      ],
    },
    requested_at: iso(-3280),
    decision_due_at: iso(3600),
    expires_at: iso(7200),
    decision_at: null,
    source_audit_event_id: "ver-uc2-001",
    latest_audit_event_id: "ver-uc2-001",
    latest_verdict: "approval_required",
    latest_reason: "Grant exists but requires approval before connector execution.",
    connector_invocation_id: null,
    grant_ref: "tool_grant:grant-uc2-engagement-send-write",
    policy_version_refs: {
      approval_policy_ref: "approval_policy.engagement_letter_send_write.local.v1",
      sla_policy_ref: "approval_sla.engagement_letter_send_write.local.v1",
    },
    trace_join: {},
    updated_at: iso(-3280),
  },
];

export const routing: RoutingEntry[] = [
  {
    route_id: "rt-default",
    match: "classifier:enquiry_classification:demo",
    agent_role: "classifier",
    task_kind: "enquiry_classification",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider: "local",
    model: "uc1-happy-path-v1",
    parameters: { temperature: 0.2 },
    budget_usd: 0.01,
    fallback_policy: { on_provider_error: "escalate" },
    lifecycle_state: "approved",
  },
  {
    route_id: "rt-fallback",
    match: "request_drafter:missing_data_request_draft:demo",
    agent_role: "request_drafter",
    task_kind: "missing_data_request_draft",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider: "local",
    model: "uc1-happy-path-v1",
    parameters: { temperature: 0.3 },
    budget_usd: 0.01,
    fallback_policy: { on_provider_error: "escalate" },
    lifecycle_state: "approved",
  },
];

export const providers: ProviderEntry[] = [
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    display_name: "Local structured boundary",
    provider_kind: "local",
    lifecycle_state: "approved",
    credential_required: false,
    secret_ref_names: [],
    missing_credentials_behaviour: "allow",
    data_boundary: { mode: "local_only", stores_customer_content: false },
    operational_limits: { default_timeout_ms: 1000, max_retries: 0 },
    audit: { owner: "agent-runtime", change_ref: "2A-02" },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "deepseek",
    display_name: "DeepSeek API",
    provider_kind: "commercial",
    lifecycle_state: "disabled",
    credential_required: true,
    secret_ref_names: ["DEEPSEEK_API_KEY"],
    missing_credentials_behaviour: "disable_provider",
    data_boundary: { mode: "external_api", stores_customer_content: true },
    operational_limits: { default_timeout_ms: 30000, max_retries: 2 },
    audit: { owner: "agent-runtime", change_ref: "r4-provider-verification" },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "openai",
    display_name: "OpenAI API",
    provider_kind: "commercial",
    lifecycle_state: "disabled",
    credential_required: true,
    secret_ref_names: ["OPENAI_API_KEY"],
    missing_credentials_behaviour: "disable_provider",
    data_boundary: { mode: "external_api", stores_customer_content: true },
    operational_limits: { default_timeout_ms: 30000, max_retries: 2 },
    audit: { owner: "agent-runtime", change_ref: "r4-provider-verification" },
  },
];

export const providerModels: ProviderModelEntry[] = [
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    model_id: "uc1-happy-path-v1",
    display_name: "UC1 local structured model",
    lifecycle_state: "approved",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 8192,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0,
      output_usd_per_1m_tokens: 0,
    },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "deepseek",
    model_id: "deepseek-v4-flash",
    display_name: "DeepSeek V4 Flash",
    lifecycle_state: "disabled",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 1000000,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0.14,
      output_usd_per_1m_tokens: 0.28,
    },
  },
  {
    catalogue_id: "provider-catalogue.local.seed",
    provider_id: "openai",
    model_id: "gpt-5.4-mini-2026-03-17",
    display_name: "GPT-5.4 mini pinned snapshot",
    lifecycle_state: "disabled",
    supported_task_kinds: [
      "enquiry_classification",
      "context_gathering",
      "enquiry_qualification",
      "missing_data_request_draft",
      "missing_data_request_validation",
    ],
    supports_structured_output: true,
    context_window_tokens: 400000,
    cost_policy: {
      currency: "USD",
      input_usd_per_1m_tokens: 0.75,
      output_usd_per_1m_tokens: 4.5,
    },
  },
];

export const routeVersions: RouteVersionEntry[] = [
  {
    route_id: "11000000-0000-4000-8000-000000000004",
    route_version: 1,
    lifecycle_state: "approved",
    agent_role: "request_drafter",
    task_kind: "missing_data_request_draft",
    tenant_tier: "demo",
    runtime_route_id: "recorded-replay",
    provider_catalogue_id: "provider-catalogue.local.seed",
    provider_id: "local",
    model_id: "uc1-happy-path-v1",
    parameters: { temperature: 0.3 },
    budget_usd: 0.01,
    max_latency_ms: 5000,
    fallback_policy: {
      mode: "escalate",
      fallback_reasons: ["provider_error", "timeout", "rate_limited", "budget_exceeded"],
    },
    eval_required: true,
    eval_fixture_refs: [
      "chorus/eval/fixtures/uc1_happy_path.json",
      "chorus/eval/fixtures/uc1_validator_redraft.json",
      "chorus/eval/fixtures/uc1_accepted_routing.json",
      "chorus/eval/fixtures/uc1_referred_routing.json",
      "chorus/eval/fixtures/uc1_declined_routing.json",
    ],
    promotion: { change_ref: "2A-02", approved_by: "architecture-docs" },
    created_at: iso(-2_592_000),
  },
];

export const evalRuns: EvalRunSummary[] = [
  {
    run_id: "eval-2026-04-28-1830",
    fixture: "uc1.golden",
    status: "passed",
    pass_count: 14,
    fail_count: 0,
    duration_ms: 38_400,
    finished_at: iso(-39_600),
  },
  {
    run_id: "eval-2026-04-28-1900",
    fixture: "uc1.escalation",
    status: "failed",
    pass_count: 11,
    fail_count: 2,
    duration_ms: 41_900,
    finished_at: iso(-37_200),
  },
];
