"""Connector port primitives: tool specs, adapter protocol, registry.

This is the abstraction the Tool Gateway dispatches through (ADR 0020 /
R3 Phase 1 decision 3). One adapter per sandbox connector; each adapter
declares the family of tools it serves through `ToolSpec`s. The registry
indexes the declared tool names to their `(adapter, ToolSpec)` pair so
the gateway can resolve, validate, and invoke without per-tool branching.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol
from uuid import UUID

from pydantic import BaseModel


@dataclass(frozen=True)
class ConnectorContext:
    """Per-invocation correlation context the gateway passes to the adapter."""

    tenant_id: str
    correlation_id: str
    workflow_id: str


@dataclass(frozen=True)
class ConnectorResult:
    """Successful connector dispatch result.

    `connector_invocation_id` is generated by the adapter and threaded into
    the gateway verdict and audit event so a single tool call can be
    correlated to the connector-side action it produced.
    """

    connector_invocation_id: UUID
    output: dict[str, Any]


class ConnectorError(RuntimeError):
    """Raised when a sandbox connector rejects an authorised call."""


class ConnectorTransientError(ConnectorError):
    """Raised when the rejection is retryable (transport or backend wobble)."""


class ConnectorRegistryError(RuntimeError):
    """Raised when the registry cannot resolve a requested tool name."""


@dataclass(frozen=True)
class ToolSpec:
    """The contract a tool exposes through its connector adapter.

    `argument_contract` is the Pydantic model the gateway validates raw
    arguments against before dispatch; `return_contract_ref` is the
    declared `$id` of the schema the connector's output is expected to
    satisfy (the gateway carries it into audit and replay).
    """

    tool_name: str
    argument_contract: type[BaseModel]
    return_contract_ref: str


class ConnectorAdapter(Protocol):
    """The interface every connector adapter implements.

    `adapter_id` is the stable identifier used in audit and observability.
    `tool_specs()` is the source of truth for which tools this adapter
    serves; the registry builds its tool-to-adapter index from these
    specs. `invoke()` receives arguments already validated against
    `ToolSpec.argument_contract` and the per-invocation context.
    """

    @property
    def adapter_id(self) -> str: ...

    def tool_specs(self) -> Sequence[ToolSpec]: ...

    def invoke(
        self,
        *,
        tool_name: str,
        mode: str,
        context: ConnectorContext,
        arguments: BaseModel,
    ) -> ConnectorResult: ...


class ConnectorRegistry:
    """One-shot registry of connector adapters keyed by declared tool name."""

    def __init__(self) -> None:
        self._adapters: dict[str, ConnectorAdapter] = {}
        self._tools: dict[str, tuple[ConnectorAdapter, ToolSpec]] = {}

    def register(self, adapter: ConnectorAdapter) -> None:
        if adapter.adapter_id in self._adapters:
            raise ConnectorRegistryError(
                f"Connector adapter {adapter.adapter_id!r} already registered"
            )
        specs = list(adapter.tool_specs())
        for spec in specs:
            existing = self._tools.get(spec.tool_name)
            if existing is not None:
                raise ConnectorRegistryError(
                    f"Tool {spec.tool_name!r} already provided by adapter "
                    f"{existing[0].adapter_id!r}; conflict with {adapter.adapter_id!r}"
                )
        self._adapters[adapter.adapter_id] = adapter
        for spec in specs:
            self._tools[spec.tool_name] = (adapter, spec)

    def resolve(self, tool_name: str) -> tuple[ConnectorAdapter, ToolSpec]:
        if tool_name not in self._tools:
            raise ConnectorRegistryError(f"No connector adapter registered for tool {tool_name!r}")
        return self._tools[tool_name]

    def tool_names(self) -> list[str]:
        return sorted(self._tools)

    def adapter_ids(self) -> list[str]:
        return sorted(self._adapters)


__all__ = [
    "ConnectorAdapter",
    "ConnectorContext",
    "ConnectorError",
    "ConnectorRegistry",
    "ConnectorRegistryError",
    "ConnectorResult",
    "ConnectorTransientError",
    "ToolSpec",
]
