/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ToolVerdictsRouteImport } from "./routes/tool-verdicts"
import { Route as RoutingRouteImport } from "./routes/routing"
import { Route as RegistryRouteImport } from "./routes/registry"
import { Route as GrantsRouteImport } from "./routes/grants"
import { Route as EvalRouteImport } from "./routes/eval"
import { Route as DecisionTrailRouteImport } from "./routes/decision-trail"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkflowsWorkflowIdRouteImport } from "./routes/workflows.$workflowId"

const ToolVerdictsRoute = ToolVerdictsRouteImport.update({
  id: "/tool-verdicts",
  path: "/tool-verdicts",
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: "/routing",
  path: "/routing",
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: "/registry",
  path: "/registry",
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: "/grants",
  path: "/grants",
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: "/eval",
  path: "/eval",
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionTrailRoute = DecisionTrailRouteImport.update({
  id: "/decision-trail",
  path: "/decision-trail",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/decision-trail": typeof DecisionTrailRoute
  "/eval": typeof EvalRoute
  "/grants": typeof GrantsRoute
  "/registry": typeof RegistryRoute
  "/routing": typeof RoutingRoute
  "/tool-verdicts": typeof ToolVerdictsRoute
  "/workflows/$workflowId": typeof WorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/decision-trail": typeof DecisionTrailRoute
  "/eval": typeof EvalRoute
  "/grants": typeof GrantsRoute
  "/registry": typeof RegistryRoute
  "/routing": typeof RoutingRoute
  "/tool-verdicts": typeof ToolVerdictsRoute
  "/workflows/$workflowId": typeof WorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/decision-trail": typeof DecisionTrailRoute
  "/eval": typeof EvalRoute
  "/grants": typeof GrantsRoute
  "/registry": typeof RegistryRoute
  "/routing": typeof RoutingRoute
  "/tool-verdicts": typeof ToolVerdictsRoute
  "/workflows/$workflowId": typeof WorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/decision-trail"
    | "/eval"
    | "/grants"
    | "/registry"
    | "/routing"
    | "/tool-verdicts"
    | "/workflows/$workflowId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/decision-trail"
    | "/eval"
    | "/grants"
    | "/registry"
    | "/routing"
    | "/tool-verdicts"
    | "/workflows/$workflowId"
  id:
    | "__root__"
    | "/"
    | "/decision-trail"
    | "/eval"
    | "/grants"
    | "/registry"
    | "/routing"
    | "/tool-verdicts"
    | "/workflows/$workflowId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionTrailRoute: typeof DecisionTrailRoute
  EvalRoute: typeof EvalRoute
  GrantsRoute: typeof GrantsRoute
  RegistryRoute: typeof RegistryRoute
  RoutingRoute: typeof RoutingRoute
  ToolVerdictsRoute: typeof ToolVerdictsRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tool-verdicts": {
      id: "/tool-verdicts"
      path: "/tool-verdicts"
      fullPath: "/tool-verdicts"
      preLoaderRoute: typeof ToolVerdictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routing": {
      id: "/routing"
      path: "/routing"
      fullPath: "/routing"
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/registry": {
      id: "/registry"
      path: "/registry"
      fullPath: "/registry"
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/grants": {
      id: "/grants"
      path: "/grants"
      fullPath: "/grants"
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/eval": {
      id: "/eval"
      path: "/eval"
      fullPath: "/eval"
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decision-trail": {
      id: "/decision-trail"
      path: "/decision-trail"
      fullPath: "/decision-trail"
      preLoaderRoute: typeof DecisionTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId"
      path: "/workflows/$workflowId"
      fullPath: "/workflows/$workflowId"
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionTrailRoute: DecisionTrailRoute,
  EvalRoute: EvalRoute,
  GrantsRoute: GrantsRoute,
  RegistryRoute: RegistryRoute,
  RoutingRoute: RoutingRoute,
  ToolVerdictsRoute: ToolVerdictsRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
